### ISSUE TITLE
Update contribution financial type when line item financial type is updated

### ISSUE THREAD

**Issue by mfb** [JMAConsulting/biz.jmaconsulting.lineitemedit#32] opened 2019-02-08 19:25 UTC
If the line item financial type is updated, this extension doesn't update the parent contribution's financial type, and they will be out of sync in any reports, etc.

Civi core now "freezes" the contribution financial type, so admins cannot manually sync the line item and contribution financial types.

I would say this extension should automatically update the parent contribution's financial type.

**Comment by eileenmcnaughton** [comment] 2019-02-08 21:32
I would lean towards just exposing the option to change it - the contribution could have several types at the line item level

**Comment by mfb** [comment] 2019-02-08 23:58
That works for me.

There might be cases where someone edits just the line item or just the contribution and they get out of sync, but that's probably not a big deal, and can always be manually fixed.

**Comment by JoeMurray** [comment] 2019-02-09 02:28
KISS: let people edit the contrib and line item financial types separately. The problem is there are many possible ways of making it more convenient that vary based on use cases that are not the same for everyone..

**Comment by mfb** [comment] 2019-02-25 22:52
Would @Monish or anyone else be able to take a look at this?

**Comment by monishdeb** [comment] 2019-07-11 10:43
@mfb I agree with you and it makes sense for contribution with single line-item. But suppose a contribution has multiple line-items, where each item has different FT then parent contribution. In such case how we can decide the contribution's FT!


So here's my plan:
1. Simply update the contribution's FT if there's single line-item FT change
2. Expose the contributions FT (like @eileenmcnaughton suggested) if there are multiple line-items 

What do you think?

**Comment by JoeMurray** [comment] 2019-07-11 17:00
Maybe put the Contribution Financial Type just above the Line Item Financial Type with help text if it is changed 'NB: The Contribution Financial Type is not used in Financial Data exports, and is deprecated and scheduled to be removed in a future version of CiviCRM as it does not accurately represent cases where different line items of a contribution have different financial types.'

**Comment by mfb** [comment] 2019-10-11 05:37
This all sounds great to me.

**Comment by mfb** [comment] 2020-02-13 02:22
We're still interested in this feature - we use the contribution financial type in reports etc.  Was anyone working on it? :)

**Comment by JoeMurray** [comment] 2020-02-13 16:44
This is currently an unfunded feature request. We're very busy unfortunately and have not been able to make time for pro bono projects. This would be near the top of them.

**Comment by mfb** [comment] 2020-02-13 19:31
The PR at #51 would resolve this issue for us, by syncing the contribution's financial type when it's updated on a line item, and the contribution only has one line item.

It doesn't do anything to make the contribution financial type editable when there are multiple line items, as suggested by @monishdeb - but it seems like that feature could be added in a followup PR.

(Side note: I was thinking perhaps this extension should use database transactions, so that all these changes to different records are made atomically?  But that would also be for another PR :)

**Comment by monishdeb** [comment] 2020-07-17 06:25
@mfb I have made this improvement under PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/55 . Please have a look.

**Comment by monishdeb** [comment] 2021-05-05 06:05
Closing the ticket as PR #55 is merged which fixes the current issue, also included in latest [2.4](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/releases/tag/2.4) release

**Closed as completed by monishdeb** 2021-05-05 06:05 UTC
