### ISSUE TITLE
"unable to reach server" error when editing contribution

### ISSUE THREAD

**Issue by MtnPavlas** [JMAConsulting/biz.jmaconsulting.lineitemedit#34] opened 2019-03-16 16:00 UTC
when the Line Item Edit extension is enabled, clicking on "Edit" button for a contribution results in the following error: "Unable to reach the server. Please refresh this page in your browser and try again."
When the extension is disabled, contributions can be edited just fine.

I enabled debugging and backtrace on our test environment, and didn't see anything obvious in the log. 

This is on Edit Line Item 2.0, CiviCRM 5.10.4 and Joomla 3.9.4

I'd be happy to grant access to our test env if someone is willing to take a look. Thank you!

**Comment by MegaphoneJon** [comment] 2019-03-16 17:01
If you right-click "Edit" and select "Open in new tab" you should get more detailed error reporting.

**Comment by MtnPavlas** [comment] 2019-03-18 04:57
thanks, MetaphoneJon, for the tip; the only extra thing I get out of this is:
_CRM_Core_Exception: Invalid currency "$" in /home/evergr55/public_html/a-test/administrator/components/com_civicrm/civicrm/CRM/Core/Smarty/plugins/modifier.crmMoney.php on line 51_

any thoughts what might be causing this?

**Comment by JoeMurray** [comment] 2019-03-18 17:19
A recent change in how core handles currencies is likely the cause. @monishdeb could you look into this first week of April if not before. Thanks.

**Comment by JoeMurray** [comment] 2019-03-18 17:21
@MegaphoneJon thx for responding here. @MtnPavlas this may be a duplicate...we'll see what @monishdeb says.

**Comment by MtnPavlas** [comment] 2019-04-01 19:49
Thanks, guys ... just thought I'd follow up. Any chance to take a look? I could simply comment out the new lines in the money.php file, but since the change was security related, I'd rather not do that.

**Comment by MtnPavlas** [comment] 2019-04-07 04:22
@monishdeb , any chance you could look into this?
The following seems to be where the change occurred:

https://lab.civicrm.org/dev/core/commit/bff4492ddf285d10960af4ce0848c3185b457c7f#c567a7e948838e1cd318c530a0d922220600c2b6

Thank you so much

**Comment by monishdeb** [comment] 2019-04-07 13:46
@MtnPavlas actually this was fixed against the latest master branch and here's the [commit](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/commit/d2ac58dfcff2dd7a801010d25c39be760e4b1dd0#diff-cdc0f215e5c1a44de9ea1637677b4795L929) Can you please pull the latest code?

**Comment by MtnPavlas** [comment] 2019-04-07 16:26
Thank you so much, @monishdeb - I patched my instance of the Line Item Edit extension per the commit above in our test environment, and it works great. Thanks!
Are you planning on posting a new version to be installed via CiviCRM?

**Comment by monishdeb** [comment] 2019-05-13 14:26
@MtnPavlas glad that patch worked for you. And yes I am going to publish a new version on next week. Stay tuned :)

**Comment by monishdeb** [comment] 2019-05-13 14:26
Closing this tikcet now

**Closed as completed by monishdeb** 2019-05-13 14:26 UTC
Labels: bug
